### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Soldier233** [SchoolUniform/RealSurvival#1]
在新玩家进入服务器，没有触发任何RealSurvival的提示的情况下
输入/rs state会NPE
因为优化的问题，防止假人，建议输入/rs state之后检查是否有资料缓存，如果没有的话新建缓存
这样的话既不报错，也不会造成恶意卡顿

**Comment by SmileYik** [comment]
了解了，感谢提出这个问题！

**Comment by boyufu** [comment]
0.2.4版本 %rs_temperature% 变量无效

**Comment by SmileYik** [comment]
我将会在下个版本修复,感谢提出,你可以试着带个装备在装备栏看看,或者带有temperature标签的装备
@icecream1507
