### ISSUE TITLE
初次安装下，玩家有很小间隔的被增加buff导致屏幕抽风

### ISSUE THREAD

**Issue by Sokwva** [SchoolUniform/RealSurvival#12]
服务器软件：CatServer-4292748
核心版本：1.12.2

初次安装此插件，进入游戏之后，人物会被在很小的间隔内加上快速的buff，然后消失；这样导致了玩家屏幕的闪动。

**Comment by SmileYik** [comment]
抱歉这么晚看见, 请去看wiki里RandomDay的配置, 找到有关风的两个选项, 都设置为0即可.
