### ISSUE TITLE
風調為0後 畫面還是會抽動

### ISSUE THREAD

**Issue by steven11304** [SchoolUniform/RealSurvival#13]
Paper 1.16.5

之前有人回報說看到畫面會抽動
你有說把風調為0即可
但是我調為0 在world世界畫面還是會抽動
以下是配製
world:
  SPRING:
    duration: 13
    humidity: 70/80
    wind-speed: 0.0/0.0
    wind-frequency: 0.0/0.0
    rain-frequency: 0.56/0.65
    base-temperature: 45/65
    day-temperature: 0.00002/0.00006
    night-temperature: 0.00002/0.00006
    rain-temperature: 3/6
  SUMMER:
    duration: 11
    humidity: 70/80
    wind-speed: 0.0/0.0
    wind-frequency: 0.0/0.0
    rain-frequency: 0.56/0.65
    base-temperature: 45/65
    day-temperature: 0.00002/0.00006
    night-temperature: 0.00002/0.00006
    rain-temperature: 3/6
  AUTUMN:
    duration: 21
    humidity: 70/80
    wind-speed: 0.0/0.0
    wind-frequency: 0.0/0.0
    rain-frequency: 0.56/0.65
    base-temperature: 45/65
    day-temperature: 0.00002/0.00006
    night-temperature: 0.00002/0.00006
    rain-temperature: 3/6
  WINTER:
    duration: 11
    humidity: 70/80
    wind-speed: 0.0/0.0
    wind-frequency: 0.0/0.0
    rain-frequency: 0.56/0.65
    base-temperature: 45/65
    day-temperature: 0.00002/0.00006
    night-temperature: 0.00002/0.00006
    rain-temperature: 3/6
  UNKNOW:
    duration: 37
    humidity: 70/80
    wind-speed: 0.0/0.0
    wind-frequency: 0.0/0.0
    rain-frequency: 0.56/0.65
    base-temperature: 45/65
    day-temperature: 0.00002/0.00006
    night-temperature: 0.00002/0.00006
    rain-temperature: 3/6
  day:
    today:
      day: 2
      season: SPRING
      humidity: 73.92942429896189
      wind-speed: 0.0
      wind-frequency: 0.0
      rain-frequency: 0.5659077785905563
      base-temperature: 47.6
      day-temperature: 2.8861890547066107E-5
      night-temperature: 3.42290753177876E-5
      rain-temperature: 4.686614223479176
    tomorrow:
      day: 3
      season: SPRING
      humidity: 76.5243744172542
      wind-speed: 0.0
      wind-frequency: 0.0
      rain-frequency: 0.6211114753962595
      base-temperature: 60.9
      day-temperature: 2.9186046555332263E-5
      night-temperature: 5.119798534632572E-5
      rain-temperature: 5.367490626836467

**Comment by steven11304** [comment]
上面說的抽動 就是畫面 會一直放大、縮小

**Comment by SmileYik** [comment]
请在config.yml里将buff效果时间延长, 具体看https://github.com/SmileYik/RealSurvival/wiki/Config.yml

buff效果名是SPEED

效果格式如下

```
#效果名,持续时间,效果强度,触发几率
```

如果没用的话格式应该是这个

```
#效果名,效果强度,持续时间,触发几率
```

两个之前其中一个, 具体哪个我有点忘记了不好意思, 
持续时间是游戏刻, 1秒=20游戏刻
