### ISSUE TITLE
1.13版本问题

### ISSUE THREAD

**Issue by NyanMeow** [SchoolUniform/RealSurvival#3]
1. 在1.13版本中使用此插件会存在这3个debuff，无法接触
![TIM截图20180811174708.png](https://i.loli.net/2018/08/11/5b6eb0b811414.png)
![TIM截图20180811174507.png](https://i.loli.net/2018/08/11/5b6eb0b81b0ea.png)
2. 1.13版本即使config允许了白天睡觉但照样不行
![TIM截图20180811174714.png](https://i.loli.net/2018/08/11/5b6eb0b82d0a1.png)

**Comment by SmileYik** [comment]
1: https://github.com/SchoolUniform/RealSurvival/wiki/Q&A#q-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E6%B2%A1%E6%9C%89%E5%BE%97%E7%97%85%E4%BD%86%E6%98%AF%E4%B8%80%E7%9B%B4%E9%83%BD%E6%9C%89debuff%E5%91%A2
2: emm, 看这个消息, 貌似是别的插件干预了耶.

**Comment by NyanMeow** [comment]
2那个提示为1.13原生自带的

**Comment by SchoolUniform** [comment]
我可以很明确的告诉你，我没有写过这句话。
你可以把语言文件拿出来看看有没有这句话，语言文件我写的我都不知道我写了这句话。
你可以单独把插件拿出来测试。

**Comment by NyanMeow** [comment]
我的意思是这个提示是1.13**客户端**新加的

**Comment by SmileYik** [comment]
好的,实在不好意思,最近断网挺久加上开学了心情有些不好.
这个你可以暂时不用这个功能,以后会进行更新的,感谢支持以及感谢你能提出问题,谢谢.
