### ISSUE TITLE
Title Maneger的问题

### ISSUE THREAD

**Issue by wdljt** [SchoolUniform/RealSurvival#4]
现在应该还是有解决办法，换到非常老的PlaceHolderAPI（未实验）
报错信息：
[PlaceholderAPI] RealSurvival is currently using a deprecated method to hook into PlaceholderAPI. Placeholders for that plugin no longer work. Please consult [School_Uniform] and urge them to update it ASAP.

**Comment by wdljt** [comment]
已测试回退PAPI的版本有用，但还是希望解决这一问题

**Comment by SmileYik** [comment]
是这样的,在做了
