### ISSUE TITLE
关于%rs_disease%的问题

### ISSUE THREAD

**Issue by TLSteve** [SchoolUniform/RealSurvival#7]
（原帖里的papi变量忘记改了害得我找了半天问题hhhc）
这个papi貌似有点问题...?
%rs_disease% 身体状况 | body information
在冻结的区域可以显示冻结中...但是一到开启的区域 就直接显示%rs_disease%
![image](https://user-images.githubusercontent.com/66633960/90630475-aa90ca00-e253-11ea-8ddb-27a10053be75.png)
![image](https://user-images.githubusercontent.com/66633960/90630497-b5e3f580-e253-11ea-9abb-3b1cd381bc64.png)
不知道是不是bug还是我设置有问题...
使用/papi parse me %rs_disease% 也是有这个问题

**Comment by SmileYik** [comment]
啊这个在改呢QwQ, 是bug呢
