### ISSUE TITLE
体温的判定有问题

### ISSUE THREAD

**Issue by NKDark** [SchoolUniform/RealSurvival#9]
在开创造测试 站岩浆里体温有降有增
![image](https://user-images.githubusercontent.com/22477622/100566506-301b2000-3301-11eb-896b-a1f41181afef.png)

**Comment by SmileYik** [comment]
emm 应该是正常现象, 在老版本中, 温度是实时变化的. 在配置文件"config.yml"中"status.temperature.block"(新版下是这个位置)配置下能配置方块的温度, 而默认的配置中并没有对岩浆这一方块的温度进行定义.
